### ISSUE TITLE
Seems to be broken with latest Elixir

### ISSUE THREAD

**Issue by progmars** [GreanMaster/laravel-elixir-uglify#2]
Tried to use with current Elixir 3.4.3 and received error:
"Cannot find module 'laravel-elixir/node_modules/gulp-rename"

The problem is that Elixir does not include gulp-rename and other dependencies any more, so you cannot look for them in Elixir's node_modules folder but have to add as your library dependencies.

**Comment by panudetjt** [comment]
Thank for report, I'll check that for now :smile:

for this time I recommend you to downgrade Elixir to keep running your work.

**Comment by njbarrett** [comment]
I'm getting this error using the plugin:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/node_modules/gulp-if'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/dev.landguide.juicebox.com.au/node_modules/laravel-elixir-uglify/index.js:3:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/dev.landguide.juicebox.com.au/gulpfile.js:6:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

Will this be updated for the newest Laravel Elixir?

**Comment by panudetjt** [comment]
I have just rewrite my plugin to lastest Laravel Elixir, You should try it with lastest version. 

sorry for very late :'(

Hope you enjoy it :)

**Comment by GreanMaster** [comment]
close #2
